### ISSUE TITLE
[HW1] hw1 decorator 관련 질문 사항

### ISSUE THREAD

**Issue by ariadne240** [swsnu/swppfall2020#13]
안녕하세요.
`safe_internet_fetch`를 구현할 때,
```
2) safe_internet_fetch
... This decorator will decorate the fetch_top_1000 function to handle the situations where fetching fails due to an invalid url or internet connection error by throwing BabyFetchException. You can catch the above error using [urllib.error.URLError] (https://docs.python.org/3/library/urllib.error.html) ...
```
라고 되어 있는데 이는 decorator에서 try except를 이용해 URLError를 catch하고 그 때 추가로 BabyFetchException을 raise 하라는 뜻인가요?
또 `check_filename_existence`를 구현할 때
```
If there is no such file with the given filename argument of the function to decorate, this decorator has to raise the custom BabynameFileNotFoundException with custom error message: No such file: {filename}.
```
라고 되어 있는데 이는 위와 달리 IOError를 catch해서 BabynameFileNotFoundException을 raise 하는 대신 os.path.exists 등을 이용하여 '파일이 존재하는지'만 판단 후 없을 경우에 raise하라는 뜻이 맞나요?
그리고
```
You can assume that the filename argument is the first argument for the function to decorate.
```
라고 되어 있는데, 이는 decorator는 무슨 function을 decorate할지 미리 알 수 없기 때문으로 보입니다. 그런데 그러면 예시
```
>>> BabynameParser("./babydata", 1900)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "babyname_parser.py", line 61, in decorated
    raise BabynameFileNotFoundException("No such file: {}".format(filename))
babyname_parser.BabynameFileNotFoundException: No such file: ./babydata/1900.html
```
에서 첫 번째 argument는 `./babydata`에 한정되는 것이 아닌가요? 그러면 `1900.html`에 대한 정보는 표시할 수 없을 것 같습니다.

**Comment by hy00nc** [comment]
1. decorator가 argument로 받은 function에 대해서 해당 function에서 URLError가 발생했을 때 그것을 catch하고 BabyFetchException을 raise하게 작성하시면 됩니다. 이 외에 다른 Exception이 발생하지 않습니다

2. 마찬가지로 BabynameFileNotFoundException 외에 다른 Exception이 나지 않도록 작성하시면 됩니다. IOError catch하는 방법도 있을 것이고 그 외에도 다양한 방법이 있을 수 있습니다.

3. decorator 정의가 BabynameParser 정의와 다르게 작성이 되어있네요.. BabynameParser 정의에 따르면 directory위치와 year 정보를 argument로 받아서 파일 이름을 생성하도록 되어있습니다. (e.g. `./babydata/1990.html`) check_filename_existence의 경우에도 해당 경우를 가정합니다. Readme, comment 수정해놓도록 하겠습니다.

**Comment by ariadne240** [comment]
답변 감사합니다.
