### ISSUE TITLE
[HW3]testing 채점 관련 질문

### ISSUE THREAD

**Issue by kslim99** [swsnu/swppfall2020#146]
평가 방식에 대해 질문이 있습니다. 
현재 테스트는 모두 PASS로 뜨나 다음과 같은 메시지는 계속 뜨고 있습니다:
● Console

    console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Not implemented: window.alert
          at module.exports (/home/lks9907/swpp_homework/hw3/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
          at alert (/home/lks9907/swpp_homework/hw3/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:594:7)
          at Login.loginHandler (/home/lks9907/swpp_homework/hw3/src/container/Login/Login.js:31:13)
          at onClick (/home/lks9907/swpp_homework/hw3/src/container/Login/Login.js:75:63)
          at HTMLUnknownElement.callCallback (/home/lks9907/swpp_homework/hw3/node_modules/react-dom/cjs/react-dom.development.js:188:14)
          at invokeEventListeners (/home/lks9907/swpp_homework/hw3/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
          at HTMLUnknownElementImpl._dispatch (/home/lks9907/swpp_homework/hw3/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (/home/lks9907/swpp_homework/hw3/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (/home/lks9907/swpp_homework/hw3/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
          at HTMLUnknownElement.dispatchEvent (/home/lks9907/swpp_homework/hw3/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21) undefined

container 쪽의 거의 모든 파일에 이런 식의 메시지가 같이 나오는데, pass만 했다면 무시하면 되나요? 

그리고 npm test -- --coverage를 실행하면 store쪽에 있는 파일들에 대한 테스트를 돌리지 않는데, 혹시 그 테스트 결과도 나오게 하는 방법이 있나요, 아니면 실습 시간에 설명해 주신 yarn 을 이용한 방법으로 계속 테스트해야 하나요?

**Comment by jiyewise** [comment]
저도 저 에러가 떴었는데, spyAlert = jest.spyOn(window, 'alert')을 사용해서 해결하였습니다..!

**Comment by cheezafizz** [comment]
window.alert = jest.fn()로도 간단히 해결할 수 있습니다

**Comment by hy00nc** [comment]
테스트에 영향을 주는 에러가 아니라면 괜찮을 것 같습니다.

yarn을 사용했을 때는 제대로 모두 테스트가 되나요? 그렇다면 yarn을 이용해서 테스트하겠습니다.
