### ISSUE TITLE
[HW1] Error handling on fetch_top_1000

### ISSUE THREAD

**Issue by cheezafizz** [swsnu/swppfall2020#21]
In cases of network connection failure and wrong URL, the written code seems to work well and show proper error prompt message,
but when you have an internet connection but cannot connect to the website (probably due to VPN or other issues discussed on some previous issues), the error handler prints the following message :

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~", line 30, in inner
    except urllib.error.URLError:
TypeError: catching classes that do not inherit from BaseException is not allowed

I know that this is not the desirable result, but I see no way how to handle this problem.
Is it necessary to show constant error message like in other cases or should I just ignore it?

**Comment by hy00nc** [comment]
1. 해당 케이스는 채점 시 고려하지 않습니다. 현상과 관련하여 이슈 #12에 보시면 ssa.gov 사이트를 mocking해서 채점 할 예정이기 때문에 걱정하지 않으셔도 됩니다.

2. 채점 시 파일/함수마다 테스트를 진행합니다. 즉 run.py는 미리 준비된 html로 테스트하니 fetch.py의 정상 작동 여부와는 상관 없습니다.

**Comment by cheezafizz** [comment]
감사합니다.
