### ISSUE TITLE
[HW2] document is not defined 에러 관련 질문입니다.

### ISSUE THREAD

**Issue by Haessun** [swsnu/swppfall2020#44]
안녕하세요, HW2를 실행시키는 부분에 있어서 해당 에러가 발생하여 문의드립니다.
터미널에 node base.js를 실행시키면,
    document.addEventListener('DOMContentLoaded', cb);
    ^

ReferenceError: document is not defined
    at whenReady (/Users/admin/Desktop/5-1/소개원실/HW/swpp-hw2-Haessun/base.js:7:5)
    at Object.<anonymous> (/Users/admin/Desktop/5-1/소개원실/HW/swpp-hw2-Haessun/base.js:125:1)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)

와 같은 에러가 계속 발생하는데, 혹시 제가 개발 환경을 설정하는 부분에 있어서 문제가 있는 것인지 잘 모르겠어서 질문 드립니다.
(실습pdf에서 설치하라고 알려주신 것들은 전부 설치해놓은 상태입니다.(extensions포함))

감사합니다!

**Comment by hy00nc** [comment]
안녕하세요
현재 HW2는 node 명령어를 통해서 단독으로 js 파일을 실행시키는 구조가 아닌, `index.html` 과 연결되어 브라우저로 html 파일을 열면 브라우저의 javascript engine에서 실행되는 구조입니다. 따라서 단독으로 base.js를 실행시키시면 해당 에러가 발생하게 됩니다 (document is not defined).

 HW2를 실행시키는 방법은 [Readme:How-to-start](https://github.com/swsnu/swppfall2020/tree/master/hw2#how-to-start)에 자세하게 나와있으니 그대로 따라하시면 될 거 같습니다.
참고로 말씀드리자면 파일 변경 후 브라우저 창을 다시 load 하시면 변경 된 코드가 반영됩니다.

**Comment by Haessun** [comment]
답변 감사드립니다!
